[imdb]
user_id = ""
watchlist_id = ""
[imdb.cookies]
id = ""

[filelist]
url = "http://filelist.io"
preferred_resolution = 2160
[filelist.auth]
username = ""
password = ""
torrentdir = ""

[polling]
new_movies_minutes = 5
longterm_hours = 3